-- Fallback libretro joypad constants. Lutro normally provides these globals,
-- but defining them keeps keyboard-only development and tests deterministic.
RETRO_DEVICE_ID_JOYPAD_B        = RETRO_DEVICE_ID_JOYPAD_B or 1
RETRO_DEVICE_ID_JOYPAD_Y        = RETRO_DEVICE_ID_JOYPAD_Y or 2
RETRO_DEVICE_ID_JOYPAD_SELECT   = RETRO_DEVICE_ID_JOYPAD_SELECT or 3
RETRO_DEVICE_ID_JOYPAD_START    = RETRO_DEVICE_ID_JOYPAD_START or 4
RETRO_DEVICE_ID_JOYPAD_UP       = RETRO_DEVICE_ID_JOYPAD_UP or 5
RETRO_DEVICE_ID_JOYPAD_DOWN     = RETRO_DEVICE_ID_JOYPAD_DOWN or 6
RETRO_DEVICE_ID_JOYPAD_LEFT     = RETRO_DEVICE_ID_JOYPAD_LEFT or 7
RETRO_DEVICE_ID_JOYPAD_RIGHT    = RETRO_DEVICE_ID_JOYPAD_RIGHT or 8
RETRO_DEVICE_ID_JOYPAD_A        = RETRO_DEVICE_ID_JOYPAD_A or 9
RETRO_DEVICE_ID_JOYPAD_X        = RETRO_DEVICE_ID_JOYPAD_X or 10
RETRO_DEVICE_ID_JOYPAD_L        = RETRO_DEVICE_ID_JOYPAD_L or 11
RETRO_DEVICE_ID_JOYPAD_R        = RETRO_DEVICE_ID_JOYPAD_R or 12
RETRO_DEVICE_ID_JOYPAD_L2       = RETRO_DEVICE_ID_JOYPAD_L2 or 13
RETRO_DEVICE_ID_JOYPAD_R2       = RETRO_DEVICE_ID_JOYPAD_R2 or 14
RETRO_DEVICE_ID_JOYPAD_L3       = RETRO_DEVICE_ID_JOYPAD_L3 or 15
RETRO_DEVICE_ID_JOYPAD_R3       = RETRO_DEVICE_ID_JOYPAD_R3 or 16
